Repository smart-village-solutions/smart-village-app-mainserver, pull requests merged in 2020-07, with the labels that each got.

#141 feat(static contents): add scope for data type
  app/controllers/static_contents_controller.rb
  app/models/static_content.rb
  app/views/static_contents/index.html.erb
Labels: enhancement

#143 fix(content editor): fix creation of JSON static contents
  app/models/static_content.rb
  app/views/app_user_contents/_form.html.erb
  app/views/app_user_contents/show.html.erb
  app/views/static_contents/_form.html.erb
  app/views/static_contents/show.html.erb
  spec/models/static_content_spec.rb
Labels: bug

#144 feat: extend devise session timeout
  config/initializers/devise.rb
Labels: enhancement

#148 refactor: scope event records to upcoming ones
  app/graphql/resolvers/event_records_search.rb
  app/models/data_resources/event_record.rb
Labels: enhancement

#150 refactor: add specific branch for gitlab-ci build
  .gitlab-ci.yml
Labels: enhancement

#151 fix: update resolver methods to succeed when combined with arrays
  app/graphql/resolvers/event_records_search.rb
Labels: bug, enhancement

#152 feat: add alive check endpoint for the mobile app
  app/controllers/application_controller.rb
  config/routes.rb
Labels: enhancement
