Repository smart-village-solutions/smart-village-app-mainserver, pull requests merged in 2021-05, with the labels that each got.

#212 feat(static contents): handle json errors
  app/views/static_contents/_form.html.erb
  app/views/static_contents/show.html.erb
Labels: bug, enhancement

#221 secure delayjob push retry on expo error
  app/services/push_notification.rb
Labels: bug

#222 Visible-Scope zu relevanten DatatResources hinzugefügt und im Category Counter verwendet
  app/graphql/types/query_types/category_type.rb
  app/models/data_resources/attraction.rb
  app/models/data_resources/event_record.rb
  app/models/data_resources/generic_item.rb
  app/models/data_resources/news_item.rb
  app/models/data_resources/resource_modules/category.rb
Labels: enhancement
