Repository smart-village-solutions/smart-village-app-mainserver, pull requests merged in 2022-03, with the labels that each got.

#300 fix(waste calendar): adjust time zone for delayed jobs
  app/models/data_resources/waste/device_registration.rb
Labels: bug, enhancement

#302 fix: add missing auth before action to /categories
  app/controllers/categories_controller.rb
Labels: bug

#305 Send minio config to CMS when user logs in
  app/controllers/users/sessions_controller.rb
Labels: enhancement

#306 fix(static content): nil version
  app/models/static_content.rb
Labels: bug, refactoring

#303 fix(static contents): add fallback format for old app versions
  app/graphql/types/query_type.rb
Labels: bug, enhancement, refactoring
