Repository smart-village-solutions/smart-village-app-mainserver, pull requests merged in 2022-11, with the labels that each got.

#356 [Snyk] Fix for 1 vulnerabilities
  Gemfile
Labels: dependencies

#355 [Snyk] Fix for 1 vulnerabilities
  Gemfile
Labels: dependencies

#358 feat(push notifications): add GraphQL for sending to all devices
  app/controllers/notification/devices_controller.rb
  app/graphql/mutations/send_push_notification.rb
  app/graphql/types/mutation_type.rb
  app/views/notification/devices/_form.html.erb
  app/views/notification/devices/_send_notification.html.erb
  app/views/notification/devices/_send_notifications.html.erb
  app/views/notification/devices/index.html.erb
Labels: enhancement, refactoring

#359 feat(push notifications): add data provider id to send to
  app/graphql/mutations/send_push_notification.rb
  app/graphql/types/input_types/push_notification_data_input.rb
  app/views/notification/devices/_send_notification.html.erb
Labels: enhancement

#361 Prevent duplicate entries of pickuptimes
  app/graphql/mutations/create_waste_pick_up_time.rb
Labels: enhancement

#364 fix(waste_exporter) Remove empty param parts for address search in waste exporter
  app/controllers/notification/wastes_controller.rb
Labels: bug

#363 Public Confirmation and Delete Controller
  app/controllers/public/confirm_records_controller.rb
  app/controllers/public_controller.rb
  app/views/layouts/application.html.erb
  app/views/layouts/doorkeeper/admin.html.erb
  app/views/layouts/doorkeeper/application.html.erb
  app/views/layouts/partials/_head.html.erb
  app/views/layouts/public.html.erb
  app/views/public/confirm_records/confirm.html.erb
  app/views/public/confirm_records/error.html.erb
  config/routes.rb
Labels: enhancement

#362 feat: add mutation to create message for generic items
  app/controllers/public/confirm_records_controller.rb
  app/controllers/public_controller.rb
  app/graphql/mutations/create_generic_item_message.rb
  app/graphql/types/mutation_type.rb
  app/models/data_resources/generic_item.rb
  app/models/data_resources/generic_item/message.rb
  app/views/layouts/application.html.erb
  app/views/layouts/doorkeeper/admin.html.erb
  app/views/layouts/doorkeeper/application.html.erb
  app/views/layouts/partials/_head.html.erb
  app/views/layouts/public.html.erb
  app/views/public/confirm_records/confirm.html.erb
  app/views/public/confirm_records/error.html.erb
  config/routes.rb
  db/migrate/20221121114916_create_generic_item_messages.rb
Labels: enhancement

#365 feat(noticeboard): mail to notify creators
  app/graphql/mutations/create_generic_item.rb
  app/mailers/noticeboard_mailer.rb
  app/models/data_resources/generic_item.rb
  app/views/mailers/noticeboard/notify_creator.text.erb
  spec/mailers/previews/noticeboard_mailer_preview.rb
Labels: enhancement

#366 feat(noticeboard): mail to notify creators on new message for entry
  app/mailers/noticeboard_mailer.rb
  app/models/data_resources/generic_item.rb
  app/models/data_resources/generic_item/message.rb
  app/views/mailers/noticeboard/new_message_for_entry.text.erb
  spec/mailers/previews/noticeboard_mailer_preview.rb
Labels: enhancement

#367 feat: cleanup notification devices
  app/controllers/notification/devices_controller.rb
  app/jobs/send_single_push_notification_job.rb
  app/jobs/waste_notification_job.rb
  app/models/data_resources/news_item.rb
  app/services/push_notification.rb
Labels: enhancement, refactoring

#370 feat(noticeboard): add new role
  app/controllers/accounts_controller.rb
  app/models/data_provider.rb
  app/views/accounts/_form.html.erb
Labels: enhancement

#368 feat(push notifications): create model for storing timings, connect to generic items and create mutation to schedule
  app/graphql/mutations/schedule_push_notification.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_types/generic_item_type.rb
  app/graphql/types/query_types/push_notification_data_type.rb
  app/graphql/types/query_types/push_notification_type.rb
  app/models/data_resources/generic_item.rb
  app/models/notification/push.rb
  app/services/push_notification.rb
  bin/start-cron.sh
  db/migrate/20221125161012_create_notification_pushes.rb
  db/migrate/20221128112410_change_is_recurring_to_integer.rb
  db/migrate/20221128115505_add_content_fields_for_notification_pushes.rb
  spec/factories/generic_items.rb
  spec/factories/notification_pushes.rb
  spec/graphql/mutations/schedule_push_notification_spec.rb
  spec/models/notification/push_spec.rb
Labels: enhancement
