Repository smart-village-solutions/smart-village-app-mainserver, pull requests merged in 2022-01, with the labels that each got.

#273 [SVA-398] Search admin interface
  app/assets/stylesheets/buttons.scss
  app/controllers/accounts_controller.rb
  app/controllers/notification/devices_controller.rb
  app/controllers/static_contents_controller.rb
  app/models/concerns/searchable.rb
  app/models/notification/device.rb
  app/models/static_content.rb
  app/models/user.rb
  app/views/accounts/index.html.erb
  app/views/application/_search_form.html.erb
  app/views/notification/devices/index.html.erb
  app/views/static_contents/index.html.erb
  config/locales/en.yml
  spec/models/concerns/searchable_spec.rb
Labels: enhancement

#272 [SVA-397] Add pagination
  Gemfile
  Gemfile.lock
  app/controllers/notification/devices_controller.rb
  app/controllers/oauth/applications_controller.rb
  app/controllers/static_contents_controller.rb
  app/views/accounts/index.html.erb
  app/views/notification/devices/index.html.erb
  app/views/oauth/applications/index.html.erb
  app/views/static_contents/index.html.erb
Labels: enhancement

#278 Fix Sorting PRs
  Gemfile
  app/controllers/static_contents_controller.rb
  spec/controllers/static_contents_controller_spec.rb
  spec/models/static_content_spec.rb
  spec/support/controller_macros.rb
Labels: refactoring

#279 hotfix: pagination for accounts
  app/controllers/accounts_controller.rb
Labels: bug
