Repository smart-village-solutions/smart-village-app-mainserver, pull requests merged in 2022-02, with the labels that each got.

#283 [SVA-308] Add exclude filter for newsItemsDataProviders query
  app/graphql/resolvers/event_records_search.rb
  app/graphql/resolvers/generic_item_search.rb
  app/graphql/resolvers/news_items_search.rb
  app/graphql/resolvers/points_of_interest_search.rb
  app/graphql/resolvers/tours_search.rb
  app/graphql/types/query_type.rb
  app/models/data_resources/attraction.rb
  app/models/data_resources/event_record.rb
  app/models/data_resources/generic_item.rb
  app/models/data_resources/news_item.rb
Labels: enhancement

#264 feat(static contents): add versioned returns
  app/graphql/types/query_type.rb
  app/models/static_content.rb
  db/migrate/20220117182809_add_version_to_static_contents.rb
  db/schema.rb
  public/schema.graphql
  public/schema.json
  schema.graphql
  schema.json
Labels: enhancement

#226 chore(graphql public json file): update content type to json
  app/graphql/types/query_type.rb
  app/graphql/types/query_types/public_json_file_type.rb
  public/schema.graphql
  public/schema.json
  schema.graphql
  schema.json
Labels: enhancement, refactoring

#269 Create and edit static contents
  app/controllers/accounts_controller.rb
  app/graphql/mutations/create_or_update_static_content.rb
  app/graphql/mutations/create_or_update_survey_poll.rb
  app/graphql/mutations/destroy_record.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/query_types/public_html_file_type.rb
  app/graphql/types/query_types/public_json_file_type.rb
  app/models/data_provider.rb
  app/models/static_content.rb
  app/models/survey/poll.rb
  app/views/accounts/_form.html.erb
  config/locales/de.yml
  public/schema.graphql
  public/schema.json
  schema.graphql
  schema.json
  spec/graphql/mutations/create_or_update_static_content_spec.rb
Labels: enhancement

#284 feat(static contents): index, show, edit versions
  app/views/static_contents/_form.html.erb
  app/views/static_contents/index.html.erb
  app/views/static_contents/show.html.erb
Labels: enhancement

#285 feat: create and edit versioned static content
  app/graphql/mutations/create_or_update_static_content.rb
  app/graphql/types/query_types/public_html_file_type.rb
  app/graphql/types/query_types/public_json_file_type.rb
  app/models/static_content.rb
  app/views/static_contents/_static_content.json.jbuilder
  public/schema.graphql
  public/schema.json
  schema.graphql
  schema.json
  spec/factories/static_contents.rb
  spec/graphql/mutations/create_or_update_static_content_spec.rb
  spec/models/static_content_spec.rb
Labels: enhancement

#210 Update records instead of deleting and creating
  app/graphql/mutations/create_event_record.rb
  app/graphql/mutations/create_generic_item.rb
  app/graphql/mutations/create_news_item.rb
  app/graphql/mutations/create_point_of_interest.rb
  app/graphql/mutations/create_tour.rb
  app/graphql/mutations/destroy_record.rb
  app/models/data_resources/attraction.rb
  app/models/data_resources/event_record.rb
  app/models/data_resources/generic_item.rb
  app/models/data_resources/news_item.rb
  app/services/resource_service.rb
  public/schema.graphql
  public/schema.json
  schema.graphql
  schema.json
  spec/services/resource_service_spec.rb
Labels: enhancement

#287 feat(category): respect ancestry in graphql queries
  app/graphql/types/query_types/category_type.rb
Labels: enhancement

#291 feat: add ability to query POIs and Tours with `categoryIds`
  app/graphql/resolvers/points_of_interest_search.rb
  app/graphql/resolvers/tours_search.rb
Labels: enhancement

#293 [SVA-271] Remove emojis from content_blocks
  Gemfile
  Gemfile.lock
  app/models/data_resources/resource_modules/content_block.rb
  spec/factories/news_items.rb
  spec/models/content_block_spec.rb
Labels: enhancement

#295 fix(cleanup service): add early returns if there is no data
  app/services/clean_up_service.rb
Labels: bug

#296 Fix saving content_block with nil values
  app/models/data_resources/resource_modules/content_block.rb
  spec/models/content_block_spec.rb
Labels: bug

#297 fix(static content): save version
  app/controllers/static_contents_controller.rb
  app/models/static_content.rb
Labels: bug
