Repository smart-village-solutions/smart-village-app-mainserver, pull requests merged in 2022-05, with the labels that each got.

#320 fix(waste notifications): convert time to correct time zone
  app/services/waste_notification.rb
Labels: bug

#321 fix(waste notification job): secure object accesses
  app/jobs/waste_notification_job.rb
Labels: bug, enhancement

#323 fix: larger db field for unique_id in external_references
  db/migrate/20220511120447_larger_unique_id_in_external_references.rb
Labels: bug

#327 Absicherung der Default Kategorien
  app/services/category_service.rb
  bin/start-cron.sh
  lib/tasks/batch_defaults.rake
Labels: enhancement

#329 Distinct category assignment by batch action
  app/services/category_service.rb
  db/migrate/20220525095902_cleanup_multiple_category_assignments.rb
Labels: bug, urgent, refactoring
